apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-app-sa
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.app.serviceAccount.automountServiceAccountToken }}

