apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.app.secret.SPRING_DATASOURCE_USERNAME | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.app.secret.SPRING_DATASOURCE_PASSWORD | b64enc | quote }}
