apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}  
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.service.name }}    
spec:
  type: {{ .Values.app.service.type }}  
  ports:
    - port: {{ .Values.app.service.port }}  
      protocol: TCP
      targetPort: {{ .Values.app.service.targetPort }}  
      nodePort: {{ .Values.app.service.nodePort }}  
  selector:
    app: {{ .Values.app.deployment.name }}     
status:
  loadBalancer: {}

