apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-mysql-sa
  namespace: {{ .Values.namespace.name }}
automountServiceAccountToken: {{ .Values.mysql.serviceAccount.automountServiceAccountToken }}
