apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mysql-network-policy
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.mysql.statefulset.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.namespace.name }}  
      podSelector:
        matchLabels:
          app: {{ .Values.app.deployment.name }}  
    ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}  
