namespace:
  name: pet-clinic-prod  

ingress:
  serviceName: app-svc  
  servicePort: 8080  



app:
  configmap:
    SPRING_JPA_HIBERNATE_DDL_AUTO: "update" 
    SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-svc:3306/petclinic" 
    SPRING_PROFILES_ACTIVE: "mysql"
    
  hpa:
    maxReplicas: 3  
    minReplicas: 1  
    targetCPUUtilizationPercentage: 60  

  deployment:
    name: app
    replicas: 2  
    container:
      image: "necipulusoyy9120/spring-petclinic-app:v1.0"  
      name: "spring-petclinic-app"

  serviceAccount:
    automountServiceAccountToken: false 

  secret:
    SPRING_DATASOURCE_USERNAME: "petclinic"  
    SPRING_DATASOURCE_PASSWORD: "petclinic"  

  service:
    name: app-svc
    type: NodePort  
    port: 8080          
    targetPort: 8080    
    nodePort: 30001  



mysql:
  serviceAccount:
    automountServiceAccountToken: false 

  secret:
    rootPassword: "petclinic"  
    database: "petclinic"          
    user: "petclinic"           
    password: "petclinic"   

  service:
    name: mysql-svc
    type: ClusterIP  
    port: 3306       
    targetPort: 3306  

  statefulset:
    name: mysql
    replicas: 1  
    container:
      image: "mysql:8.0"  
    storageClassName: "local-path"  
    storage: "1Gi"  

  pvc:
    storageClassName: "local-path"  
    storage: "1Gi"  

